// Code generated by protoc-gen-go.
// source: PhotonCommands.proto
// DO NOT EDIT!

/*
Package photongo is a generated protocol buffer package.

It is generated from these files:
	PhotonCommands.proto

It has these top-level messages:
	PhotonWrapper
	Connect
	Connect_Response
	Authenticate
	Authenticate_Response
	StartStream
	StreamStart_Response
	Heartbeat
	Heartbeat_Response
	Disconnect
*/
package photongo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolVersion int32

const (
	ProtocolVersion_NONE ProtocolVersion = 0
	ProtocolVersion_V1   ProtocolVersion = 1
)

var ProtocolVersion_name = map[int32]string{
	0: "NONE",
	1: "V1",
}
var ProtocolVersion_value = map[string]int32{
	"NONE": 0,
	"V1":   1,
}

func (x ProtocolVersion) String() string {
	return proto.EnumName(ProtocolVersion_name, int32(x))
}
func (ProtocolVersion) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Codes that can be set on any command
type StatusCodes int32

const (
	StatusCodes_UNKNOWN                StatusCodes = 0
	StatusCodes_OK                     StatusCodes = 200
	StatusCodes_PING                   StatusCodes = 201
	StatusCodes_BAD_REQUEST            StatusCodes = 400
	StatusCodes_UNAUTHORIZED           StatusCodes = 401
	StatusCodes_OLD_VERSION            StatusCodes = 402
	StatusCodes_NO_RESPONSE            StatusCodes = 403
	StatusCodes_INVALID_STREAM_KEY     StatusCodes = 406
	StatusCodes_CHANNEL_IN_USE         StatusCodes = 407
	StatusCodes_REGION_UNSUPPORTED     StatusCodes = 408
	StatusCodes_NO_MEDIA_TIMEOUT       StatusCodes = 409
	StatusCodes_INTERNAL_SERVER_ERROR  StatusCodes = 500
	StatusCodes_INTERNAL_COMMAND_ERROR StatusCodes = 501
	StatusCodes_INTERNAL_LOCAL_ERROR   StatusCodes = 502
)

var StatusCodes_name = map[int32]string{
	0:   "UNKNOWN",
	200: "OK",
	201: "PING",
	400: "BAD_REQUEST",
	401: "UNAUTHORIZED",
	402: "OLD_VERSION",
	403: "NO_RESPONSE",
	406: "INVALID_STREAM_KEY",
	407: "CHANNEL_IN_USE",
	408: "REGION_UNSUPPORTED",
	409: "NO_MEDIA_TIMEOUT",
	500: "INTERNAL_SERVER_ERROR",
	501: "INTERNAL_COMMAND_ERROR",
	502: "INTERNAL_LOCAL_ERROR",
}
var StatusCodes_value = map[string]int32{
	"UNKNOWN":                0,
	"OK":                     200,
	"PING":                   201,
	"BAD_REQUEST":            400,
	"UNAUTHORIZED":           401,
	"OLD_VERSION":            402,
	"NO_RESPONSE":            403,
	"INVALID_STREAM_KEY":     406,
	"CHANNEL_IN_USE":         407,
	"REGION_UNSUPPORTED":     408,
	"NO_MEDIA_TIMEOUT":       409,
	"INTERNAL_SERVER_ERROR":  500,
	"INTERNAL_COMMAND_ERROR": 501,
	"INTERNAL_LOCAL_ERROR":   502,
}

func (x StatusCodes) String() string {
	return proto.EnumName(StatusCodes_name, int32(x))
}
func (StatusCodes) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Reasons why the stream disconnected
type DisconnectReasons int32

const (
	DisconnectReasons_DISCONNECT_UNKNOWN        DisconnectReasons = 0
	DisconnectReasons_CLIENT_CLEAN              DisconnectReasons = 200
	DisconnectReasons_INGEST_CLEAN              DisconnectReasons = 201
	DisconnectReasons_CLIENT_ERROR_UNKNOWN      DisconnectReasons = 300
	DisconnectReasons_CLIENT_ERROR_TIMEOUT      DisconnectReasons = 301
	DisconnectReasons_CLIENT_ERROR_BAD_RESPONSE DisconnectReasons = 302
	DisconnectReasons_INGEST_ERROR_UNKNOWN      DisconnectReasons = 400
	DisconnectReasons_INGEST_ERROR_TIMEOUT      DisconnectReasons = 401
)

var DisconnectReasons_name = map[int32]string{
	0:   "DISCONNECT_UNKNOWN",
	200: "CLIENT_CLEAN",
	201: "INGEST_CLEAN",
	300: "CLIENT_ERROR_UNKNOWN",
	301: "CLIENT_ERROR_TIMEOUT",
	302: "CLIENT_ERROR_BAD_RESPONSE",
	400: "INGEST_ERROR_UNKNOWN",
	401: "INGEST_ERROR_TIMEOUT",
}
var DisconnectReasons_value = map[string]int32{
	"DISCONNECT_UNKNOWN":        0,
	"CLIENT_CLEAN":              200,
	"INGEST_CLEAN":              201,
	"CLIENT_ERROR_UNKNOWN":      300,
	"CLIENT_ERROR_TIMEOUT":      301,
	"CLIENT_ERROR_BAD_RESPONSE": 302,
	"INGEST_ERROR_UNKNOWN":      400,
	"INGEST_ERROR_TIMEOUT":      401,
}

func (x DisconnectReasons) String() string {
	return proto.EnumName(DisconnectReasons_name, int32(x))
}
func (DisconnectReasons) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PhotonWrapper struct {
	StatusCode StatusCodes          `protobuf:"varint,1,opt,name=StatusCode,enum=Photon.Commands.StatusCodes" json:"StatusCode,omitempty"`
	Command    *google_protobuf.Any `protobuf:"bytes,15,opt,name=Command" json:"Command,omitempty"`
}

func (m *PhotonWrapper) Reset()                    { *m = PhotonWrapper{} }
func (m *PhotonWrapper) String() string            { return proto.CompactTextString(m) }
func (*PhotonWrapper) ProtoMessage()               {}
func (*PhotonWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PhotonWrapper) GetStatusCode() StatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return StatusCodes_UNKNOWN
}

func (m *PhotonWrapper) GetCommand() *google_protobuf.Any {
	if m != nil {
		return m.Command
	}
	return nil
}

type Connect struct {
	ClientProtocolVersion ProtocolVersion `protobuf:"varint,1,opt,name=ClientProtocolVersion,enum=Photon.Commands.ProtocolVersion" json:"ClientProtocolVersion,omitempty"`
}

func (m *Connect) Reset()                    { *m = Connect{} }
func (m *Connect) String() string            { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()               {}
func (*Connect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Connect) GetClientProtocolVersion() ProtocolVersion {
	if m != nil {
		return m.ClientProtocolVersion
	}
	return ProtocolVersion_NONE
}

type Connect_Response struct {
	ServerProtocolVersion ProtocolVersion `protobuf:"varint,1,opt,name=ServerProtocolVersion,enum=Photon.Commands.ProtocolVersion" json:"ServerProtocolVersion,omitempty"`
	TelemetryId           string          `protobuf:"bytes,2,opt,name=TelemetryId" json:"TelemetryId,omitempty"`
	HmacKey               string          `protobuf:"bytes,3,opt,name=HmacKey" json:"HmacKey,omitempty"`
}

func (m *Connect_Response) Reset()                    { *m = Connect_Response{} }
func (m *Connect_Response) String() string            { return proto.CompactTextString(m) }
func (*Connect_Response) ProtoMessage()               {}
func (*Connect_Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Connect_Response) GetServerProtocolVersion() ProtocolVersion {
	if m != nil {
		return m.ServerProtocolVersion
	}
	return ProtocolVersion_NONE
}

func (m *Connect_Response) GetTelemetryId() string {
	if m != nil {
		return m.TelemetryId
	}
	return ""
}

func (m *Connect_Response) GetHmacKey() string {
	if m != nil {
		return m.HmacKey
	}
	return ""
}

type Authenticate struct {
	ChannelId uint32 `protobuf:"varint,1,opt,name=ChannelId" json:"ChannelId,omitempty"`
	AuthKey   string `protobuf:"bytes,2,opt,name=AuthKey" json:"AuthKey,omitempty"`
}

func (m *Authenticate) Reset()                    { *m = Authenticate{} }
func (m *Authenticate) String() string            { return proto.CompactTextString(m) }
func (*Authenticate) ProtoMessage()               {}
func (*Authenticate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Authenticate) GetChannelId() uint32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *Authenticate) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

type Authenticate_Response struct {
}

func (m *Authenticate_Response) Reset()                    { *m = Authenticate_Response{} }
func (m *Authenticate_Response) String() string            { return proto.CompactTextString(m) }
func (*Authenticate_Response) ProtoMessage()               {}
func (*Authenticate_Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type StartStream struct {
	VendorName    string `protobuf:"bytes,1,opt,name=VendorName" json:"VendorName,omitempty"`
	VendorVersion string `protobuf:"bytes,2,opt,name=VendorVersion" json:"VendorVersion,omitempty"`
	// Video Params
	HasVideo         bool   `protobuf:"varint,10,opt,name=HasVideo" json:"HasVideo,omitempty"`
	VideoCodec       string `protobuf:"bytes,11,opt,name=VideoCodec" json:"VideoCodec,omitempty"`
	VideoHeight      uint32 `protobuf:"varint,12,opt,name=VideoHeight" json:"VideoHeight,omitempty"`
	VideoWidth       uint32 `protobuf:"varint,13,opt,name=VideoWidth" json:"VideoWidth,omitempty"`
	VideoPayloadType uint32 `protobuf:"varint,14,opt,name=VideoPayloadType" json:"VideoPayloadType,omitempty"`
	VideoIngestSSRC  uint32 `protobuf:"varint,15,opt,name=VideoIngestSSRC" json:"VideoIngestSSRC,omitempty"`
	// Audio Params
	HasAudio         bool   `protobuf:"varint,30,opt,name=HasAudio" json:"HasAudio,omitempty"`
	AudioCodec       string `protobuf:"bytes,31,opt,name=AudioCodec" json:"AudioCodec,omitempty"`
	AudioPayloadType uint32 `protobuf:"varint,32,opt,name=AudioPayloadType" json:"AudioPayloadType,omitempty"`
	AudioIngestSSRC  uint32 `protobuf:"varint,33,opt,name=AudioIngestSSRC" json:"AudioIngestSSRC,omitempty"`
}

func (m *StartStream) Reset()                    { *m = StartStream{} }
func (m *StartStream) String() string            { return proto.CompactTextString(m) }
func (*StartStream) ProtoMessage()               {}
func (*StartStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StartStream) GetVendorName() string {
	if m != nil {
		return m.VendorName
	}
	return ""
}

func (m *StartStream) GetVendorVersion() string {
	if m != nil {
		return m.VendorVersion
	}
	return ""
}

func (m *StartStream) GetHasVideo() bool {
	if m != nil {
		return m.HasVideo
	}
	return false
}

func (m *StartStream) GetVideoCodec() string {
	if m != nil {
		return m.VideoCodec
	}
	return ""
}

func (m *StartStream) GetVideoHeight() uint32 {
	if m != nil {
		return m.VideoHeight
	}
	return 0
}

func (m *StartStream) GetVideoWidth() uint32 {
	if m != nil {
		return m.VideoWidth
	}
	return 0
}

func (m *StartStream) GetVideoPayloadType() uint32 {
	if m != nil {
		return m.VideoPayloadType
	}
	return 0
}

func (m *StartStream) GetVideoIngestSSRC() uint32 {
	if m != nil {
		return m.VideoIngestSSRC
	}
	return 0
}

func (m *StartStream) GetHasAudio() bool {
	if m != nil {
		return m.HasAudio
	}
	return false
}

func (m *StartStream) GetAudioCodec() string {
	if m != nil {
		return m.AudioCodec
	}
	return ""
}

func (m *StartStream) GetAudioPayloadType() uint32 {
	if m != nil {
		return m.AudioPayloadType
	}
	return 0
}

func (m *StartStream) GetAudioIngestSSRC() uint32 {
	if m != nil {
		return m.AudioIngestSSRC
	}
	return 0
}

type StreamStart_Response struct {
	IngestPort uint32 `protobuf:"varint,1,opt,name=IngestPort" json:"IngestPort,omitempty"`
}

func (m *StreamStart_Response) Reset()                    { *m = StreamStart_Response{} }
func (m *StreamStart_Response) String() string            { return proto.CompactTextString(m) }
func (*StreamStart_Response) ProtoMessage()               {}
func (*StreamStart_Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StreamStart_Response) GetIngestPort() uint32 {
	if m != nil {
		return m.IngestPort
	}
	return 0
}

type Heartbeat struct {
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Heartbeat_Response struct {
}

func (m *Heartbeat_Response) Reset()                    { *m = Heartbeat_Response{} }
func (m *Heartbeat_Response) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat_Response) ProtoMessage()               {}
func (*Heartbeat_Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Disconnect struct {
	Reason DisconnectReasons `protobuf:"varint,1,opt,name=Reason,enum=Photon.Commands.DisconnectReasons" json:"Reason,omitempty"`
}

func (m *Disconnect) Reset()                    { *m = Disconnect{} }
func (m *Disconnect) String() string            { return proto.CompactTextString(m) }
func (*Disconnect) ProtoMessage()               {}
func (*Disconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Disconnect) GetReason() DisconnectReasons {
	if m != nil {
		return m.Reason
	}
	return DisconnectReasons_DISCONNECT_UNKNOWN
}

func init() {
	proto.RegisterType((*PhotonWrapper)(nil), "Photon.Commands.PhotonWrapper")
	proto.RegisterType((*Connect)(nil), "Photon.Commands.Connect")
	proto.RegisterType((*Connect_Response)(nil), "Photon.Commands.Connect_Response")
	proto.RegisterType((*Authenticate)(nil), "Photon.Commands.Authenticate")
	proto.RegisterType((*Authenticate_Response)(nil), "Photon.Commands.Authenticate_Response")
	proto.RegisterType((*StartStream)(nil), "Photon.Commands.StartStream")
	proto.RegisterType((*StreamStart_Response)(nil), "Photon.Commands.StreamStart_Response")
	proto.RegisterType((*Heartbeat)(nil), "Photon.Commands.Heartbeat")
	proto.RegisterType((*Heartbeat_Response)(nil), "Photon.Commands.Heartbeat_Response")
	proto.RegisterType((*Disconnect)(nil), "Photon.Commands.Disconnect")
	proto.RegisterEnum("Photon.Commands.ProtocolVersion", ProtocolVersion_name, ProtocolVersion_value)
	proto.RegisterEnum("Photon.Commands.StatusCodes", StatusCodes_name, StatusCodes_value)
	proto.RegisterEnum("Photon.Commands.DisconnectReasons", DisconnectReasons_name, DisconnectReasons_value)
}

func init() { proto.RegisterFile("PhotonCommands.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 895 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x5e, 0xc7, 0xab, 0x9d, 0x49, 0x25, 0x99, 0xe9, 0x69, 0x32, 0xbb, 0x9e, 0x61, 0x35, 0x04,
	0xc3, 0x21, 0x9a, 0x43, 0x56, 0x2c, 0x12, 0x07, 0xc4, 0xc5, 0xeb, 0x34, 0x13, 0x6b, 0x92, 0x76,
	0x68, 0x3b, 0x19, 0xb1, 0x17, 0xcb, 0x93, 0x34, 0x49, 0xa4, 0xc4, 0x8e, 0xec, 0x1e, 0xa4, 0x1c,
	0x78, 0x87, 0x5d, 0x90, 0xf8, 0x79, 0x01, 0x24, 0x24, 0xe0, 0xce, 0x1b, 0xb0, 0x0f, 0xc1, 0x5b,
	0x00, 0x67, 0xe4, 0xf6, 0x4f, 0x3c, 0xc9, 0x9e, 0xb8, 0xb9, 0xbe, 0xfa, 0xba, 0xbe, 0xaf, 0xaa,
	0xab, 0x13, 0x68, 0x0e, 0xe7, 0xa1, 0x08, 0x03, 0x33, 0x5c, 0xad, 0xfc, 0x60, 0x1a, 0x77, 0xd6,
	0x51, 0x28, 0x42, 0x7c, 0x9c, 0xa2, 0x9d, 0x1c, 0x3e, 0x3f, 0x9b, 0x85, 0xe1, 0x6c, 0xc9, 0x9f,
	0xc9, 0xf4, 0xed, 0xdd, 0x57, 0xcf, 0xfc, 0x60, 0x93, 0x72, 0xf5, 0x6f, 0xa0, 0x91, 0xb2, 0x6f,
	0x22, 0x7f, 0xbd, 0xe6, 0x11, 0xfe, 0x0c, 0xc0, 0x11, 0xbe, 0xb8, 0x8b, 0xcd, 0x70, 0xca, 0x35,
	0xa5, 0xa5, 0xb4, 0x8f, 0x9e, 0x3f, 0xed, 0xec, 0x54, 0xec, 0x6c, 0x29, 0x31, 0x2b, 0xf1, 0x71,
	0x07, 0x0e, 0x32, 0x8e, 0x76, 0xdc, 0x52, 0xda, 0xb5, 0xe7, 0xcd, 0x4e, 0xaa, 0xdd, 0xc9, 0xb5,
	0x3b, 0x46, 0xb0, 0x61, 0x39, 0x49, 0xf7, 0x13, 0x7e, 0x10, 0xf0, 0x89, 0xc0, 0x63, 0x38, 0x35,
	0x97, 0x0b, 0x1e, 0x88, 0x61, 0xc2, 0x9c, 0x84, 0xcb, 0x31, 0x8f, 0xe2, 0x45, 0x18, 0x64, 0x1e,
	0x5a, 0x7b, 0x1e, 0x76, 0x78, 0xec, 0xed, 0xc7, 0xf5, 0x9f, 0x15, 0x40, 0x99, 0x86, 0xc7, 0x78,
	0xbc, 0x0e, 0x83, 0x98, 0x27, 0x62, 0x0e, 0x8f, 0xbe, 0xe6, 0xd1, 0xff, 0x16, 0x7b, 0xeb, 0x71,
	0xdc, 0x82, 0x9a, 0xcb, 0x97, 0x7c, 0xc5, 0x45, 0xb4, 0xb1, 0xa6, 0x5a, 0xa5, 0xa5, 0xb4, 0xab,
	0xac, 0x0c, 0x61, 0x0d, 0x0e, 0x7a, 0x2b, 0x7f, 0x72, 0xcd, 0x37, 0x9a, 0x2a, 0xb3, 0x79, 0xa8,
	0x7f, 0x0e, 0x75, 0xe3, 0x4e, 0xcc, 0x79, 0x20, 0x16, 0x13, 0x5f, 0x70, 0xfc, 0x14, 0xaa, 0xe6,
	0xdc, 0x0f, 0x02, 0xbe, 0xb4, 0xa6, 0xd2, 0x57, 0x83, 0x6d, 0x81, 0xa4, 0x4e, 0xc2, 0x4e, 0xea,
	0xa4, 0x2a, 0x79, 0xa8, 0x3f, 0x81, 0xd3, 0x72, 0x9d, 0xa2, 0x69, 0xfd, 0x0f, 0x15, 0x6a, 0x8e,
	0xf0, 0x23, 0xe1, 0x88, 0x88, 0xfb, 0x2b, 0x7c, 0x01, 0x30, 0xe6, 0xc1, 0x34, 0x8c, 0xa8, 0xbf,
	0x4a, 0xaf, 0xba, 0xca, 0x4a, 0x08, 0xfe, 0x10, 0x1a, 0x69, 0x94, 0x0f, 0x27, 0x15, 0xba, 0x0f,
	0xe2, 0x73, 0x38, 0xec, 0xf9, 0xf1, 0x78, 0x31, 0xe5, 0xa1, 0x06, 0x2d, 0xa5, 0x7d, 0xc8, 0x8a,
	0x58, 0x2a, 0x24, 0x1f, 0xc9, 0x6e, 0x4c, 0xb4, 0x5a, 0xa6, 0x50, 0x20, 0xc9, 0xb8, 0x64, 0xd4,
	0xe3, 0x8b, 0xd9, 0x5c, 0x68, 0x75, 0xd9, 0x64, 0x19, 0x2a, 0x2a, 0xdc, 0x2c, 0xa6, 0x62, 0xae,
	0x35, 0x24, 0xa1, 0x84, 0xe0, 0x4b, 0x40, 0x32, 0x1a, 0xfa, 0x9b, 0x65, 0xe8, 0x4f, 0xdd, 0xcd,
	0x9a, 0x6b, 0x47, 0x92, 0xb5, 0x87, 0xe3, 0x36, 0x1c, 0x4b, 0xcc, 0x0a, 0x66, 0x3c, 0x16, 0x8e,
	0xc3, 0x4c, 0xb9, 0xa4, 0x0d, 0xb6, 0x0b, 0x67, 0x3d, 0x19, 0x77, 0xd3, 0x45, 0xa8, 0x5d, 0x14,
	0x3d, 0xc9, 0x38, 0x71, 0x24, 0x3f, 0xd2, 0x9e, 0xde, 0x4b, 0x7b, 0xda, 0x22, 0x89, 0x23, 0x19,
	0x95, 0x1d, 0xb5, 0x52, 0x47, 0xbb, 0x78, 0xe2, 0x48, 0x62, 0x25, 0x47, 0xef, 0xa7, 0x8e, 0x76,
	0x60, 0xfd, 0x13, 0x68, 0xa6, 0xb7, 0x26, 0x2f, 0x70, 0xbb, 0xc8, 0x17, 0x00, 0x29, 0x6b, 0x18,
	0x46, 0x22, 0xdb, 0x92, 0x12, 0xa2, 0xd7, 0xa0, 0xda, 0xe3, 0x7e, 0x24, 0x6e, 0xb9, 0x2f, 0xf4,
	0x26, 0xe0, 0x22, 0xd8, 0xae, 0x45, 0x0f, 0xa0, 0xbb, 0x88, 0x27, 0xd9, 0x33, 0xfc, 0x14, 0x1e,
	0x31, 0xee, 0xc7, 0xc5, 0x53, 0xd0, 0xf7, 0x9e, 0xc2, 0x96, 0x9c, 0x12, 0x63, 0x96, 0x9d, 0xb8,
	0xfc, 0x00, 0x8e, 0x77, 0x1f, 0xc4, 0x21, 0x3c, 0xa4, 0x36, 0x25, 0xe8, 0x01, 0x7e, 0x04, 0x95,
	0xf1, 0x47, 0x48, 0xb9, 0xfc, 0xa5, 0x22, 0xb7, 0x30, 0xff, 0xf9, 0xc0, 0x35, 0x38, 0x18, 0xd1,
	0x6b, 0x6a, 0xdf, 0x50, 0xf4, 0x00, 0x1f, 0x40, 0xc5, 0xbe, 0x46, 0x7f, 0x2a, 0xb8, 0x0a, 0x0f,
	0x87, 0x16, 0xbd, 0x42, 0x6f, 0x14, 0x8c, 0xa0, 0xf6, 0xc2, 0xe8, 0x7a, 0x8c, 0x7c, 0x31, 0x22,
	0x8e, 0x8b, 0x5e, 0xa9, 0xf8, 0x04, 0xea, 0x23, 0x6a, 0x8c, 0xdc, 0x9e, 0xcd, 0xac, 0x97, 0xa4,
	0x8b, 0x5e, 0xab, 0x09, 0xc9, 0xee, 0x77, 0xbd, 0x31, 0x61, 0x8e, 0x65, 0x53, 0xf4, 0xad, 0x44,
	0xa8, 0xed, 0x31, 0xe2, 0x0c, 0x6d, 0xea, 0x10, 0xf4, 0x9d, 0x8a, 0x9f, 0x00, 0xb6, 0xe8, 0xd8,
	0xe8, 0x5b, 0x5d, 0xcf, 0x71, 0x19, 0x31, 0x06, 0xde, 0x35, 0xf9, 0x12, 0x7d, 0xaf, 0xe2, 0x77,
	0xe0, 0xc8, 0xec, 0x19, 0x94, 0x92, 0xbe, 0x67, 0x51, 0x6f, 0xe4, 0x10, 0xf4, 0x83, 0x64, 0x33,
	0x72, 0x65, 0xd9, 0xd4, 0x1b, 0x51, 0x67, 0x34, 0x1c, 0xda, 0xcc, 0x25, 0x5d, 0xf4, 0xa3, 0x8a,
	0x4f, 0x01, 0x51, 0xdb, 0x1b, 0x90, 0xae, 0x65, 0x78, 0xae, 0x35, 0x20, 0xf6, 0xc8, 0x45, 0x3f,
	0xa9, 0xf8, 0x1c, 0x4e, 0x2d, 0xea, 0x12, 0x46, 0x8d, 0xbe, 0xe7, 0x10, 0x36, 0x26, 0xcc, 0x23,
	0x8c, 0xd9, 0x0c, 0xfd, 0xad, 0xe2, 0x77, 0xe1, 0x71, 0x91, 0x33, 0xed, 0xc1, 0xc0, 0xa0, 0xdd,
	0x2c, 0xf9, 0x8f, 0x8a, 0xcf, 0xa0, 0x59, 0x24, 0xfb, 0xb6, 0x69, 0xf4, 0xb3, 0xd4, 0xbf, 0xea,
	0xe5, 0x5f, 0x0a, 0x9c, 0xec, 0x8d, 0x1b, 0x3f, 0x06, 0xdc, 0xb5, 0x1c, 0xd3, 0xa6, 0x94, 0x98,
	0xae, 0xb7, 0x1d, 0xde, 0x09, 0xd4, 0xcd, 0xbe, 0x45, 0xa8, 0xeb, 0x99, 0x7d, 0x62, 0xd0, 0x64,
	0x8c, 0x27, 0x50, 0xb7, 0xe8, 0x15, 0x71, 0x72, 0xe8, 0x8d, 0x92, 0xc8, 0x65, 0x2c, 0x29, 0x53,
	0x9c, 0xff, 0xb5, 0xb2, 0x97, 0xca, 0xbb, 0xfb, 0xad, 0x82, 0x2f, 0xe0, 0xec, 0x5e, 0x2a, 0xbd,
	0x91, 0x6c, 0xb6, 0xbf, 0x57, 0xd2, 0x26, 0xa4, 0xd0, 0xfd, 0xaa, 0xaf, 0xd4, 0xbd, 0x54, 0x5e,
	0xf5, 0xb5, 0xfa, 0x02, 0x5e, 0x1e, 0xae, 0xe5, 0x76, 0xcd, 0xc2, 0xdb, 0x47, 0xf2, 0x1f, 0xe2,
	0xe3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xdf, 0x50, 0x21, 0xd4, 0x06, 0x00, 0x00,
}
