// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhotonCommands.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PhotonCommands.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Photon {
namespace Commands {
class PhotonWrapperDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<PhotonWrapper> {
} _PhotonWrapper_default_instance_;
class ConnectDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Connect> {
} _Connect_default_instance_;
class Connect_ResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Connect_Response> {
} _Connect_Response_default_instance_;

namespace protobuf_PhotonCommands_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PhotonWrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PhotonWrapper, statuscode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PhotonWrapper, command_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect, clientprotocolversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect, channelid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect, authkey_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, serverprotocolversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, hmackey_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(PhotonWrapper)},
  { 6, -1, sizeof(Connect)},
  { 13, -1, sizeof(Connect_Response)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_PhotonWrapper_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Connect_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Connect_Response_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "PhotonCommands.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _PhotonWrapper_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Connect_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Connect_Response_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::InitDefaults();
  _PhotonWrapper_default_instance_.DefaultConstruct();
  _Connect_default_instance_.DefaultConstruct();
  _Connect_Response_default_instance_.DefaultConstruct();
  _PhotonWrapper_default_instance_.get_mutable()->command_ = const_cast< ::google::protobuf::Any*>(
      ::google::protobuf::Any::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\024PhotonCommands.proto\022\017Photon.Commands\032"
      "\031google/protobuf/any.proto\"h\n\rPhotonWrap"
      "per\0220\n\nStatusCode\030\001 \001(\0162\034.Photon.Command"
      "s.StatusCodes\022%\n\007Command\030\017 \001(\0132\024.google."
      "protobuf.Any\"n\n\007Connect\022\?\n\025ClientProtoco"
      "lVersion\030\001 \001(\0162 .Photon.Commands.Protoco"
      "lVersion\022\021\n\tChannelID\030\002 \001(\t\022\017\n\007AuthKey\030\003"
      " \001(\t\"d\n\020Connect_Response\022\?\n\025ServerProtoc"
      "olVersion\030\001 \001(\0162 .Photon.Commands.Protoc"
      "olVersion\022\017\n\007HmacKey\030\002 \001(\t*#\n\017ProtocolVe"
      "rsion\022\010\n\004NONE\020\000\022\006\n\002V1\020\001*\337\002\n\013StatusCodes\022"
      "\013\n\007UNKNOWN\020\000\022\007\n\002OK\020\310\001\022\t\n\004PING\020\311\001\022\020\n\013BAD_"
      "REQUEST\020\220\003\022\021\n\014UNAUTHORIZED\020\221\003\022\020\n\013OLD_VER"
      "SION\020\222\003\022\020\n\013NO_RESPONSE\020\223\003\022\031\n\024AUDIO_SSRC_"
      "COLLISION\020\224\003\022\031\n\024VIDEO_SSRC_COLLISION\020\225\003\022"
      "\027\n\022INVALID_STREAM_KEY\020\226\003\022\023\n\016CHANNEL_IN_U"
      "SE\020\227\003\022\027\n\022REGION_UNSUPPORTED\020\230\003\022\025\n\020NO_MED"
      "IA_TIMEOUT\020\231\003\022\032\n\025INTERNAL_SERVER_ERROR\020\364"
      "\003\022\033\n\026INTERNAL_COMMAND_ERROR\020\365\003\022\031\n\024INTERN"
      "AL_LOCAL_ERROR\020\366\003B\nZ\010photongob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 797);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PhotonCommands.proto", &protobuf_RegisterTypes);
  ::google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_PhotonCommands_2eproto

const ::google::protobuf::EnumDescriptor* ProtocolVersion_descriptor() {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_enum_descriptors[0];
}
bool ProtocolVersion_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* StatusCodes_descriptor() {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_enum_descriptors[1];
}
bool StatusCodes_IsValid(int value) {
  switch (value) {
    case 0:
    case 200:
    case 201:
    case 400:
    case 401:
    case 402:
    case 403:
    case 404:
    case 405:
    case 406:
    case 407:
    case 408:
    case 409:
    case 500:
    case 501:
    case 502:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PhotonWrapper::kStatusCodeFieldNumber;
const int PhotonWrapper::kCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PhotonWrapper::PhotonWrapper()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_PhotonCommands_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Photon.Commands.PhotonWrapper)
}
PhotonWrapper::PhotonWrapper(const PhotonWrapper& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_command()) {
    command_ = new ::google::protobuf::Any(*from.command_);
  } else {
    command_ = NULL;
  }
  statuscode_ = from.statuscode_;
  // @@protoc_insertion_point(copy_constructor:Photon.Commands.PhotonWrapper)
}

void PhotonWrapper::SharedCtor() {
  ::memset(&command_, 0, reinterpret_cast<char*>(&statuscode_) -
    reinterpret_cast<char*>(&command_) + sizeof(statuscode_));
  _cached_size_ = 0;
}

PhotonWrapper::~PhotonWrapper() {
  // @@protoc_insertion_point(destructor:Photon.Commands.PhotonWrapper)
  SharedDtor();
}

void PhotonWrapper::SharedDtor() {
  if (this != internal_default_instance()) {
    delete command_;
  }
}

void PhotonWrapper::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PhotonWrapper::descriptor() {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_metadata[0].descriptor;
}

const PhotonWrapper& PhotonWrapper::default_instance() {
  protobuf_PhotonCommands_2eproto::InitDefaults();
  return *internal_default_instance();
}

PhotonWrapper* PhotonWrapper::New(::google::protobuf::Arena* arena) const {
  PhotonWrapper* n = new PhotonWrapper;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PhotonWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:Photon.Commands.PhotonWrapper)
  if (GetArenaNoVirtual() == NULL && command_ != NULL) {
    delete command_;
  }
  command_ = NULL;
  statuscode_ = 0;
}

bool PhotonWrapper::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Photon.Commands.PhotonWrapper)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Photon.Commands.StatusCodes StatusCode = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_statuscode(static_cast< ::Photon::Commands::StatusCodes >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Any Command = 15;
      case 15: {
        if (tag == 122u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_command()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Photon.Commands.PhotonWrapper)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Photon.Commands.PhotonWrapper)
  return false;
#undef DO_
}

void PhotonWrapper::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Photon.Commands.PhotonWrapper)
  // .Photon.Commands.StatusCodes StatusCode = 1;
  if (this->statuscode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->statuscode(), output);
  }

  // .google.protobuf.Any Command = 15;
  if (this->has_command()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, *this->command_, output);
  }

  // @@protoc_insertion_point(serialize_end:Photon.Commands.PhotonWrapper)
}

::google::protobuf::uint8* PhotonWrapper::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Photon.Commands.PhotonWrapper)
  // .Photon.Commands.StatusCodes StatusCode = 1;
  if (this->statuscode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->statuscode(), target);
  }

  // .google.protobuf.Any Command = 15;
  if (this->has_command()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        15, *this->command_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Photon.Commands.PhotonWrapper)
  return target;
}

size_t PhotonWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Photon.Commands.PhotonWrapper)
  size_t total_size = 0;

  // .google.protobuf.Any Command = 15;
  if (this->has_command()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->command_);
  }

  // .Photon.Commands.StatusCodes StatusCode = 1;
  if (this->statuscode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->statuscode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PhotonWrapper::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Photon.Commands.PhotonWrapper)
  GOOGLE_DCHECK_NE(&from, this);
  const PhotonWrapper* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PhotonWrapper>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Photon.Commands.PhotonWrapper)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Photon.Commands.PhotonWrapper)
    MergeFrom(*source);
  }
}

void PhotonWrapper::MergeFrom(const PhotonWrapper& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Photon.Commands.PhotonWrapper)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_command()) {
    mutable_command()->::google::protobuf::Any::MergeFrom(from.command());
  }
  if (from.statuscode() != 0) {
    set_statuscode(from.statuscode());
  }
}

void PhotonWrapper::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Photon.Commands.PhotonWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PhotonWrapper::CopyFrom(const PhotonWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Photon.Commands.PhotonWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PhotonWrapper::IsInitialized() const {
  return true;
}

void PhotonWrapper::Swap(PhotonWrapper* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PhotonWrapper::InternalSwap(PhotonWrapper* other) {
  std::swap(command_, other->command_);
  std::swap(statuscode_, other->statuscode_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PhotonWrapper::GetMetadata() const {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PhotonWrapper

// .Photon.Commands.StatusCodes StatusCode = 1;
void PhotonWrapper::clear_statuscode() {
  statuscode_ = 0;
}
::Photon::Commands::StatusCodes PhotonWrapper::statuscode() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.PhotonWrapper.StatusCode)
  return static_cast< ::Photon::Commands::StatusCodes >(statuscode_);
}
void PhotonWrapper::set_statuscode(::Photon::Commands::StatusCodes value) {
  
  statuscode_ = value;
  // @@protoc_insertion_point(field_set:Photon.Commands.PhotonWrapper.StatusCode)
}

// .google.protobuf.Any Command = 15;
bool PhotonWrapper::has_command() const {
  return this != internal_default_instance() && command_ != NULL;
}
void PhotonWrapper::clear_command() {
  if (GetArenaNoVirtual() == NULL && command_ != NULL) delete command_;
  command_ = NULL;
}
const ::google::protobuf::Any& PhotonWrapper::command() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.PhotonWrapper.Command)
  return command_ != NULL ? *command_
                         : *::google::protobuf::Any::internal_default_instance();
}
::google::protobuf::Any* PhotonWrapper::mutable_command() {
  
  if (command_ == NULL) {
    command_ = new ::google::protobuf::Any;
  }
  // @@protoc_insertion_point(field_mutable:Photon.Commands.PhotonWrapper.Command)
  return command_;
}
::google::protobuf::Any* PhotonWrapper::release_command() {
  // @@protoc_insertion_point(field_release:Photon.Commands.PhotonWrapper.Command)
  
  ::google::protobuf::Any* temp = command_;
  command_ = NULL;
  return temp;
}
void PhotonWrapper::set_allocated_command(::google::protobuf::Any* command) {
  delete command_;
  command_ = command;
  if (command) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Photon.Commands.PhotonWrapper.Command)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Connect::kClientProtocolVersionFieldNumber;
const int Connect::kChannelIDFieldNumber;
const int Connect::kAuthKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Connect::Connect()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_PhotonCommands_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Photon.Commands.Connect)
}
Connect::Connect(const Connect& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  channelid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.channelid().size() > 0) {
    channelid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channelid_);
  }
  authkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.authkey().size() > 0) {
    authkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.authkey_);
  }
  clientprotocolversion_ = from.clientprotocolversion_;
  // @@protoc_insertion_point(copy_constructor:Photon.Commands.Connect)
}

void Connect::SharedCtor() {
  channelid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  authkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clientprotocolversion_ = 0;
  _cached_size_ = 0;
}

Connect::~Connect() {
  // @@protoc_insertion_point(destructor:Photon.Commands.Connect)
  SharedDtor();
}

void Connect::SharedDtor() {
  channelid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  authkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Connect::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Connect::descriptor() {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_metadata[1].descriptor;
}

const Connect& Connect::default_instance() {
  protobuf_PhotonCommands_2eproto::InitDefaults();
  return *internal_default_instance();
}

Connect* Connect::New(::google::protobuf::Arena* arena) const {
  Connect* n = new Connect;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Connect::Clear() {
// @@protoc_insertion_point(message_clear_start:Photon.Commands.Connect)
  channelid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  authkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clientprotocolversion_ = 0;
}

bool Connect::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Photon.Commands.Connect)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Photon.Commands.ProtocolVersion ClientProtocolVersion = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_clientprotocolversion(static_cast< ::Photon::Commands::ProtocolVersion >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string ChannelID = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channelid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->channelid().data(), this->channelid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Photon.Commands.Connect.ChannelID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string AuthKey = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_authkey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->authkey().data(), this->authkey().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Photon.Commands.Connect.AuthKey"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Photon.Commands.Connect)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Photon.Commands.Connect)
  return false;
#undef DO_
}

void Connect::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Photon.Commands.Connect)
  // .Photon.Commands.ProtocolVersion ClientProtocolVersion = 1;
  if (this->clientprotocolversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->clientprotocolversion(), output);
  }

  // string ChannelID = 2;
  if (this->channelid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channelid().data(), this->channelid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Photon.Commands.Connect.ChannelID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->channelid(), output);
  }

  // string AuthKey = 3;
  if (this->authkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->authkey().data(), this->authkey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Photon.Commands.Connect.AuthKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->authkey(), output);
  }

  // @@protoc_insertion_point(serialize_end:Photon.Commands.Connect)
}

::google::protobuf::uint8* Connect::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Photon.Commands.Connect)
  // .Photon.Commands.ProtocolVersion ClientProtocolVersion = 1;
  if (this->clientprotocolversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->clientprotocolversion(), target);
  }

  // string ChannelID = 2;
  if (this->channelid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channelid().data(), this->channelid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Photon.Commands.Connect.ChannelID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->channelid(), target);
  }

  // string AuthKey = 3;
  if (this->authkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->authkey().data(), this->authkey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Photon.Commands.Connect.AuthKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->authkey(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Photon.Commands.Connect)
  return target;
}

size_t Connect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Photon.Commands.Connect)
  size_t total_size = 0;

  // string ChannelID = 2;
  if (this->channelid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channelid());
  }

  // string AuthKey = 3;
  if (this->authkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->authkey());
  }

  // .Photon.Commands.ProtocolVersion ClientProtocolVersion = 1;
  if (this->clientprotocolversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->clientprotocolversion());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Connect::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Photon.Commands.Connect)
  GOOGLE_DCHECK_NE(&from, this);
  const Connect* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Connect>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Photon.Commands.Connect)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Photon.Commands.Connect)
    MergeFrom(*source);
  }
}

void Connect::MergeFrom(const Connect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Photon.Commands.Connect)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.channelid().size() > 0) {

    channelid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channelid_);
  }
  if (from.authkey().size() > 0) {

    authkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.authkey_);
  }
  if (from.clientprotocolversion() != 0) {
    set_clientprotocolversion(from.clientprotocolversion());
  }
}

void Connect::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Photon.Commands.Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Connect::CopyFrom(const Connect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Photon.Commands.Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Connect::IsInitialized() const {
  return true;
}

void Connect::Swap(Connect* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Connect::InternalSwap(Connect* other) {
  channelid_.Swap(&other->channelid_);
  authkey_.Swap(&other->authkey_);
  std::swap(clientprotocolversion_, other->clientprotocolversion_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Connect::GetMetadata() const {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Connect

// .Photon.Commands.ProtocolVersion ClientProtocolVersion = 1;
void Connect::clear_clientprotocolversion() {
  clientprotocolversion_ = 0;
}
::Photon::Commands::ProtocolVersion Connect::clientprotocolversion() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.Connect.ClientProtocolVersion)
  return static_cast< ::Photon::Commands::ProtocolVersion >(clientprotocolversion_);
}
void Connect::set_clientprotocolversion(::Photon::Commands::ProtocolVersion value) {
  
  clientprotocolversion_ = value;
  // @@protoc_insertion_point(field_set:Photon.Commands.Connect.ClientProtocolVersion)
}

// string ChannelID = 2;
void Connect::clear_channelid() {
  channelid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Connect::channelid() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.Connect.ChannelID)
  return channelid_.GetNoArena();
}
void Connect::set_channelid(const ::std::string& value) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Photon.Commands.Connect.ChannelID)
}
#if LANG_CXX11
void Connect::set_channelid(::std::string&& value) {
  
  channelid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Photon.Commands.Connect.ChannelID)
}
#endif
void Connect::set_channelid(const char* value) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Photon.Commands.Connect.ChannelID)
}
void Connect::set_channelid(const char* value, size_t size) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Photon.Commands.Connect.ChannelID)
}
::std::string* Connect::mutable_channelid() {
  
  // @@protoc_insertion_point(field_mutable:Photon.Commands.Connect.ChannelID)
  return channelid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Connect::release_channelid() {
  // @@protoc_insertion_point(field_release:Photon.Commands.Connect.ChannelID)
  
  return channelid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Connect::set_allocated_channelid(::std::string* channelid) {
  if (channelid != NULL) {
    
  } else {
    
  }
  channelid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), channelid);
  // @@protoc_insertion_point(field_set_allocated:Photon.Commands.Connect.ChannelID)
}

// string AuthKey = 3;
void Connect::clear_authkey() {
  authkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Connect::authkey() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.Connect.AuthKey)
  return authkey_.GetNoArena();
}
void Connect::set_authkey(const ::std::string& value) {
  
  authkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Photon.Commands.Connect.AuthKey)
}
#if LANG_CXX11
void Connect::set_authkey(::std::string&& value) {
  
  authkey_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Photon.Commands.Connect.AuthKey)
}
#endif
void Connect::set_authkey(const char* value) {
  
  authkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Photon.Commands.Connect.AuthKey)
}
void Connect::set_authkey(const char* value, size_t size) {
  
  authkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Photon.Commands.Connect.AuthKey)
}
::std::string* Connect::mutable_authkey() {
  
  // @@protoc_insertion_point(field_mutable:Photon.Commands.Connect.AuthKey)
  return authkey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Connect::release_authkey() {
  // @@protoc_insertion_point(field_release:Photon.Commands.Connect.AuthKey)
  
  return authkey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Connect::set_allocated_authkey(::std::string* authkey) {
  if (authkey != NULL) {
    
  } else {
    
  }
  authkey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), authkey);
  // @@protoc_insertion_point(field_set_allocated:Photon.Commands.Connect.AuthKey)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Connect_Response::kServerProtocolVersionFieldNumber;
const int Connect_Response::kHmacKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Connect_Response::Connect_Response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_PhotonCommands_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Photon.Commands.Connect_Response)
}
Connect_Response::Connect_Response(const Connect_Response& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hmackey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hmackey().size() > 0) {
    hmackey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hmackey_);
  }
  serverprotocolversion_ = from.serverprotocolversion_;
  // @@protoc_insertion_point(copy_constructor:Photon.Commands.Connect_Response)
}

void Connect_Response::SharedCtor() {
  hmackey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  serverprotocolversion_ = 0;
  _cached_size_ = 0;
}

Connect_Response::~Connect_Response() {
  // @@protoc_insertion_point(destructor:Photon.Commands.Connect_Response)
  SharedDtor();
}

void Connect_Response::SharedDtor() {
  hmackey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Connect_Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Connect_Response::descriptor() {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_metadata[2].descriptor;
}

const Connect_Response& Connect_Response::default_instance() {
  protobuf_PhotonCommands_2eproto::InitDefaults();
  return *internal_default_instance();
}

Connect_Response* Connect_Response::New(::google::protobuf::Arena* arena) const {
  Connect_Response* n = new Connect_Response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Connect_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:Photon.Commands.Connect_Response)
  hmackey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  serverprotocolversion_ = 0;
}

bool Connect_Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Photon.Commands.Connect_Response)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Photon.Commands.ProtocolVersion ServerProtocolVersion = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_serverprotocolversion(static_cast< ::Photon::Commands::ProtocolVersion >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string HmacKey = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hmackey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hmackey().data(), this->hmackey().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Photon.Commands.Connect_Response.HmacKey"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Photon.Commands.Connect_Response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Photon.Commands.Connect_Response)
  return false;
#undef DO_
}

void Connect_Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Photon.Commands.Connect_Response)
  // .Photon.Commands.ProtocolVersion ServerProtocolVersion = 1;
  if (this->serverprotocolversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->serverprotocolversion(), output);
  }

  // string HmacKey = 2;
  if (this->hmackey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hmackey().data(), this->hmackey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Photon.Commands.Connect_Response.HmacKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->hmackey(), output);
  }

  // @@protoc_insertion_point(serialize_end:Photon.Commands.Connect_Response)
}

::google::protobuf::uint8* Connect_Response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Photon.Commands.Connect_Response)
  // .Photon.Commands.ProtocolVersion ServerProtocolVersion = 1;
  if (this->serverprotocolversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->serverprotocolversion(), target);
  }

  // string HmacKey = 2;
  if (this->hmackey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hmackey().data(), this->hmackey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Photon.Commands.Connect_Response.HmacKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->hmackey(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Photon.Commands.Connect_Response)
  return target;
}

size_t Connect_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Photon.Commands.Connect_Response)
  size_t total_size = 0;

  // string HmacKey = 2;
  if (this->hmackey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hmackey());
  }

  // .Photon.Commands.ProtocolVersion ServerProtocolVersion = 1;
  if (this->serverprotocolversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->serverprotocolversion());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Connect_Response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Photon.Commands.Connect_Response)
  GOOGLE_DCHECK_NE(&from, this);
  const Connect_Response* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Connect_Response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Photon.Commands.Connect_Response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Photon.Commands.Connect_Response)
    MergeFrom(*source);
  }
}

void Connect_Response::MergeFrom(const Connect_Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Photon.Commands.Connect_Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.hmackey().size() > 0) {

    hmackey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hmackey_);
  }
  if (from.serverprotocolversion() != 0) {
    set_serverprotocolversion(from.serverprotocolversion());
  }
}

void Connect_Response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Photon.Commands.Connect_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Connect_Response::CopyFrom(const Connect_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Photon.Commands.Connect_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Connect_Response::IsInitialized() const {
  return true;
}

void Connect_Response::Swap(Connect_Response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Connect_Response::InternalSwap(Connect_Response* other) {
  hmackey_.Swap(&other->hmackey_);
  std::swap(serverprotocolversion_, other->serverprotocolversion_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Connect_Response::GetMetadata() const {
  protobuf_PhotonCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PhotonCommands_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Connect_Response

// .Photon.Commands.ProtocolVersion ServerProtocolVersion = 1;
void Connect_Response::clear_serverprotocolversion() {
  serverprotocolversion_ = 0;
}
::Photon::Commands::ProtocolVersion Connect_Response::serverprotocolversion() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.Connect_Response.ServerProtocolVersion)
  return static_cast< ::Photon::Commands::ProtocolVersion >(serverprotocolversion_);
}
void Connect_Response::set_serverprotocolversion(::Photon::Commands::ProtocolVersion value) {
  
  serverprotocolversion_ = value;
  // @@protoc_insertion_point(field_set:Photon.Commands.Connect_Response.ServerProtocolVersion)
}

// string HmacKey = 2;
void Connect_Response::clear_hmackey() {
  hmackey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Connect_Response::hmackey() const {
  // @@protoc_insertion_point(field_get:Photon.Commands.Connect_Response.HmacKey)
  return hmackey_.GetNoArena();
}
void Connect_Response::set_hmackey(const ::std::string& value) {
  
  hmackey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Photon.Commands.Connect_Response.HmacKey)
}
#if LANG_CXX11
void Connect_Response::set_hmackey(::std::string&& value) {
  
  hmackey_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Photon.Commands.Connect_Response.HmacKey)
}
#endif
void Connect_Response::set_hmackey(const char* value) {
  
  hmackey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Photon.Commands.Connect_Response.HmacKey)
}
void Connect_Response::set_hmackey(const char* value, size_t size) {
  
  hmackey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Photon.Commands.Connect_Response.HmacKey)
}
::std::string* Connect_Response::mutable_hmackey() {
  
  // @@protoc_insertion_point(field_mutable:Photon.Commands.Connect_Response.HmacKey)
  return hmackey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Connect_Response::release_hmackey() {
  // @@protoc_insertion_point(field_release:Photon.Commands.Connect_Response.HmacKey)
  
  return hmackey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Connect_Response::set_allocated_hmackey(::std::string* hmackey) {
  if (hmackey != NULL) {
    
  } else {
    
  }
  hmackey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hmackey);
  // @@protoc_insertion_point(field_set_allocated:Photon.Commands.Connect_Response.HmacKey)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Commands
}  // namespace Photon

// @@protoc_insertion_point(global_scope)
